# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNPassLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNPassLibrary
  pod 'PassLibrary', '~> 2.1.2'

end
